CREATE DATABASE DB_CHALLENGE_BLOG
GO
USE DB_CHALLENGE_BLOG
GO
CREATE TABLE Tabla(
ID INT IDENTITY(1,1),
Titulo VARCHAR(100) not null,
Contenido VARCHAR(300) null,
Imagen VARCHAR(300) null,
Categoria CHAR null,
Fecha_Creacion DATE not null,
) 
GO
ALTER TABLE Tabla
ADD CONSTRAINT PK_tabla_ID PRIMARY KEY(ID)
GO
ALTER TABLE Tabla
ADD UNIQUE(Titulo)
